# version: '3'
services:
 mysql:
   image: mysql:5.7
   container_name: mysql
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time_zone='+8:00' --lower_case_table_names=1
   restart: always
   environment:
     MYSQL_DATABASE: "cjp-cli-dev" # 设置初始数据库
     MYSQL_USER: "cjp" # 设置登录用户
     MYSQL_PASSWORD: "Abc@123*" # 设置登录密码
     # 上面三个参数需要连接到 MySQL 容器并使用 root 用户授权才可以使用
     MYSQL_ROOT_PASSWORD: "P@ssword!123#" #设置root帐号密码
     TZ: "Asia/Shanghai"
   ports:
     - 3306:3306
   volumes:
     - ./db:/var/lib/mysql #数据文件挂载
     - ./conf:/etc/mysql/conf.d #配置文件挂载
     - ./log:/var/log/mysql #日志文件挂载
     - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql  # 初始化数据库和用户
#  redis:
#    image: redis:6
#    container_name: redis
#    command: redis-server --appendonly yes
#    volumes:
#      - /mydata/redis/data:/data #数据文件挂载
#    ports:
#      - 6379:6379
#  nginx:
#    image: nginx:1.10
#    container_name: nginx
#    volumes:
#      - /mydata/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
#      - /mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
#      - /mydata/nginx/log:/var/log/nginx #日志文件挂载
#    ports:
#      - 80:80
#  rabbitmq:
#    image: rabbitmq:3.8.8-management
#    container_name: rabbitmq
#    volumes:
#      - /mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
#      - /mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
#    ports:
#      - 5672:5672
#      - 15672:15672
#  elasticsearch:
#    image: elasticsearch:7.16.3
#    container_name: elasticsearch
#    environment:
#      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
#      - "discovery.type=single-node" #以单一节点模式启动
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
#    volumes:
#      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
#    ports:
#      - 9200:9200
#      - 9300:9300
#  kibana:
#    image: kibana:6.4.0
#    container_name: kibana
#    links:
#      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
#    depends_on:
#      - elasticsearch #kibana在elasticsearch启动之后再启动
#    environment:
#      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
#    ports:
#      - 5601:5601
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   volumes:
  #     - /mydata/mongo/db:/data/db #数据文件挂载
  #   ports:
  #     - 27017:27017
#  minio:
#    image: minio/minio:latest
#    container_name: minio
#    command: server /data
#    restart: always
#    environment:
#      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
#      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
#    volumes:
#      - /mydata/minio/data:/data
#      - /mydata/minio/config:/root/.minio
#    ports:
#      - 9000:9000
